### ISSUE TITLE
hire professional copywriter and branding expert to proofread the content copy

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/horizontalsystems.github.io#10]

**Comment by HarryHeights** [comment]
Hello @esengulov I am a copywriter and can help with proofreading your content.

**Comment by esengulov** [comment]
> Hello @esengulov I am a copywriter and can help with proofreading your content.

Thanks for the followup Harry, 

I will have to pass not he offer and we are still not settled on the message/content itself.
