### ISSUE TITLE
change "DApps vs Regular Apps" image  on the home

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/horizontalsystems.github.io#14]
the top image needs to be adjusted to better match the page layout.

Suggesting following changes:

- [ ] match image backgrounders with the page background
- [ ] remove image border
- [ ] make titles greyish.
- [ ] make the image smaller in width/height bu 30-40%

**Comment by TalgatNurdinov** [comment]
![dapps_image2](https://user-images.githubusercontent.com/42367908/49501545-4f5f4e00-f89d-11e8-87bc-21524ca36aed.png)
