### ISSUE TITLE
change the HS DAO image on About page

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/horizontalsystems.github.io#15]
the HS DAO needs to be adjusted to better match the page layout.

Suggesting following changes:

- [x] match image backgrounders with the page background
- [x] remove image border
- [x] make titles greyish.
- [x] make the image smaller in width/height bu 30-40%

**Comment by esengulov** [comment]
@TalgatNurdinov I think the current image is overly complicated, simplify  it please.

**Comment by TalgatNurdinov** [comment]
https://github.com/horizontalsystems/horizontalsystems.github.io/commit/650f2d08724b89ff671479fb613cbfda7f56ff46
