### ISSUE TITLE
for app page: Need all app screens in a single gallery-like Image

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/horizontalsystems.github.io#16]
We need an image that would consist of 9 smaller images each showing a specific section in the app. We need this for README on repository as well as the app page on the website.

| 1) Balance Tab | 4) Transactions Tab | 7) Settings |
| ------------- |:-------------:| -----:|
| 2) Receive | 5) Tx info | 8) Base currency | 
| 3) Send |  6) full tx info | 9) Language | 

- [x] make sure that all 9 screens in the image has last approved look
- [x] gallery image look for iOS
- [x] gallery image look for Android
- [ ] on iOS-repository (README). Needs an iOS version
- [ ] on Android-repository (README). Needs an Android version
- [ ] on website (bank wallet page). feel free to use either iOS or Android version for the gallery image. https://horizontalsystems.io/dapps/bank-wallet

**Comment by esengulov** [comment]
@TalgatNurdinov the gallery screenshots on following pages are outdated:

- [ ] on iOS-repository (README). Needs an iOS version
- [ ] on Android-repository (README). Needs an Android version
- [ ] on website (bank wallet page). feel free to use either iOS or Android version for the gallery image. https://horizontalsystems.io/dapps/bank-wallet

**Comment by TalgatNurdinov** [comment]
![bankwallet_screenshots_android](https://user-images.githubusercontent.com/42367908/50762384-f9fccf00-1296-11e9-9697-98dc5e217171.png)
![bankwallet_screenshots_ios](https://user-images.githubusercontent.com/42367908/50762385-fa956580-1296-11e9-97c5-44f31c87af97.png)
