### ISSUE TITLE
simplify the apps image on homepage

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/horizontalsystems.github.io#18]
https://horizontalsystems.io/assets/images/dapps.png

I find it overwhelming and bloated

- [x] remove borders
- [x] remove text
- [x] make it smaller in width/height
- [x] don't use black (or close) colors. the text is primary element here

**Comment by TalgatNurdinov** [comment]
![hs_dapps](https://user-images.githubusercontent.com/42367908/49791401-9eecc080-fd5a-11e8-8bdb-3b5f598c2b75.png)

**Comment by TalgatNurdinov** [comment]
https://github.com/horizontalsystems/horizontalsystems.github.io/commit/650f2d08724b89ff671479fb613cbfda7f56ff46
