### ISSUE TITLE
slightly change bank wallet image on site's home

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/horizontalsystems.github.io#20]
- [x] under the BANK WALLET title in the image subtitle instead of "decentralized cryptocurrency wallet" add "Control Your Money!"

- [x] the BANK WALLET title make it standout a bit less as it currently overlaps with the text header title for the section

- [x] add static Play Market / App Store labels below the text in the image

**Comment by TalgatNurdinov** [comment]
![dao_platform](https://user-images.githubusercontent.com/42367908/50209094-21016880-039d-11e9-85a6-2f7a9e0dde77.png)
