### ISSUE TITLE
add new graphic images

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/horizontalsystems.github.io#23]
- [x] need graphic for Bitcoin SPV kit
- [x] need graphic for Ethereum light client

**Comment by TalgatNurdinov** [comment]
https://zpl.io/VxR37Mm

**Comment by esengulov** [comment]
https://github.com/horizontalsystems/horizontalsystems.github.io/commit/37744575f3e30a99974e5444ec99054112088bcd
