### ISSUE TITLE
Display Weekly Commit Graphs Under each repo

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/horizontalsystems.github.io#26]
Get on this ticket only after the following two issues are closed:

- [ ] https://github.com/horizontalsystems/horizontalsystems.github.io/issues/25
- [ ] https://github.com/horizontalsystems/horizontalsystems.github.io/issues/22

If Github API allows let's display the weekly commit graph ([like the bar graph here](https://github.com/horizontalsystems/bank-wallet-android/graphs/commit-activity)) below each repo description on libraries page, http://horizontalsystems.io/libraries .

**Comment by tlg01** [comment]
It will take some time to display commits graph, we can implement it some time later.

**Comment by esengulov** [comment]
> It will take some time to display commits graph, we can implement it some time later.

agreed, not essential at this point. consider it done!
