### ISSUE TITLE
Fix the elements position and margins on mobile view 

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/horizontalsystems.github.io#29]
<img width="491" alt="Screen Shot 2019-03-25 at 2 19 18 PM" src="https://user-images.githubusercontent.com/42367908/54904743-82d7ee00-4f09-11e9-8040-e4307eb77579.png">

**Comment by tlg01** [comment]
I have applied new design here #30. So, closing this as irrelevant
