### ISSUE TITLE
Minor Design Fixes

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/horizontalsystems.github.io#31]
- [ ] Adjust the minimum width to 360
- [ ] Remove Home (About > Apps > Code)
- [ ] App Name on the minimal width shold be bottom of app icon
- [ ] Add font for "Blockchain Library" 
- [ ] Fix the position of  code badges on the min width #

**Comment by tlg01** [comment]
Not relevant as applied new design
