### ISSUE TITLE
create diagrams for the website

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/horizontalsystems.github.io#5]
we need three diagrams for the homepage on horizontalsystems.io

- [x] diagram explaining DAO concept
- [x] diagram explaining dApp concept
- [x] diagram explaining Horizontal Systems DAO

**Comment by TalgatNurdinov** [comment]
<img width="956" alt="screen shot 2018-10-18 at 10 58 16 am" src="https://user-images.githubusercontent.com/42367908/47132266-df810e00-d2c4-11e8-850f-08f822155752.png">

<img width="874" alt="screen shot 2018-10-18 at 10 58 26 am" src="https://user-images.githubusercontent.com/42367908/47132265-df810e00-d2c4-11e8-9ed7-ddab08c9452f.png">

**Comment by esengulov** [comment]
![hs_dao](https://user-images.githubusercontent.com/8611762/47547077-d243cf00-d915-11e8-9782-dd4c72844c48.png)
![dapps](https://user-images.githubusercontent.com/8611762/47547078-d243cf00-d915-11e8-97bd-80abf2a7e13c.png)
![dao](https://user-images.githubusercontent.com/8611762/47547079-d243cf00-d915-11e8-81ee-1bd8fcd047f2.png)

@TalgatNurdinov finished!
